### PR TITLE
Don't check hostname

### PR DESCRIPTION
**Pull request by ahoulgrave**

### CODE REVIEW

**Comment by oliverguenther** [comment]
Could you explain your goal with this PR? In its current form, this change would allow `http://google.com/wp/12345` to be matched as a reference to a ticket on OpenProject.

**Comment by ahoulgrave** [comment]
People usually copy and paste the url, but sometimes i happens that the openproject is accessible via different urls and people mess up. Also it's possible that the Settings.host_name has any value.

I understand what you say, and now realize that the solution isn't this, but maybe to match the packages by `/\#([0-9]+)\s(?:.+)/`.

This, of course, would break compatibility on already implemented openprojects. What do you think about this? Maybe try to match this format, and then try to match the current one?

Thanks in advance.

**Comment by oliverguenther** [comment]
We could probably introduce a somewhat more unique identifier to ticket identifiers such as `OP#1234` that would be matched. Using just `<hash><number>` will also interfere with open issues and PR on Github, so I'm not sure that will work well.

**Comment by oliverguenther** [comment]
I've done exactly that in https://github.com/finnlabs/openproject-github_integration/pull/20

**Pull request closed without merging**
